[package]
name = "reducto-mode-3"
version = "0.1.0"
edition = "2021"
authors = ["Reducto Team"]
description = "High-performance differential synchronization compression system"
license = "MIT"

[dependencies]
# L1 Core: Fundamental Rust features (no external dependencies)
# - Ownership, lifetimes, traits, Result/Option, RAII, newtype pattern

# L2 Standard Library: Collections, iterators, smart pointers, thread safety
# - HashMap, Vec, Arc, Mutex, Send/Sync

# L3 External Dependencies: Ecosystem crates
blake3 = { version = "1.5", features = ["serde"] }        # Strong cryptographic hashing
bincode = "1.3"       # Efficient binary serialization
serde = { version = "1.0", features = ["derive"] }
zstd = "0.13"         # High-performance compression
memmap2 = "0.9"       # Memory-mapped file access
hashbrown = "0.14"    # High-performance HashMap
anyhow = "1.0"        # Application error handling
thiserror = "1.0"     # Library error definitions
uuid = { version = "1.0", features = ["v4", "serde"] }

[dev-dependencies]
proptest = "1.0"      # Property-based testing
criterion = "0.5"     # Benchmarking framework
tempfile = "3.0"      # Temporary files for testing
tokio-test = "0.4"    # Async testing utilities

# Benchmarks will be added in later tasks
# [[bench]]
# name = "rolling_hash"
# harness = false
# 
# [[bench]]
# name = "compression"
# harness = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
debug = true